# Generated by Django 6.0.5 on 2026-05-15 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-last_seen",),
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        help_text="E.164 format, e.g. +18091234567",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_es", models.CharField(max_length=120)),
                ("description_en", models.TextField(blank=True)),
                ("description_es", models.TextField(blank=True)),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords used by the fallback classifier when no LLM is available.",
                    ),
                ),
                (
                    "expected_commission_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "default_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_services",
                        to="concierge.provider",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name_en"),
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="providers", to="concierge.service"
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_code", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("no_show", "No show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_commission_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("raw_first_message", models.TextField(blank=True)),
                ("extracted_fields", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="concierge.guest",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="concierge.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="concierge.service",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("guest_in", "From guest"),
                            ("guest_out", "To guest"),
                            ("provider_in", "From provider"),
                            ("provider_out", "To provider"),
                            ("system_out", "System → user"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_phone", models.CharField(blank=True, max_length=20)),
                ("to_phone", models.CharField(blank=True, max_length=20)),
                ("body", models.TextField()),
                (
                    "wa_message_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="concierge.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["guest", "status"], name="concierge_t_guest_i_280f11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["provider", "status"], name="concierge_t_provide_841f7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["ticket", "direction"], name="concierge_m_ticket__b9f8ea_idx"
            ),
        ),
    ]
