# Generated by Django 6.0.5 on 2026-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_fr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_fr",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
