# Generated by Django 6.0.5 on 2026-05-17 16:36

from django.conf import settings as dj_settings
from django.db import migrations, models


def seed_singleton(apps, schema_editor):
    SiteSettings = apps.get_model("concierge", "SiteSettings")
    host = getattr(dj_settings, "HOST_NAME", "Host")
    apt = getattr(dj_settings, "HOST_APARTMENT_LABEL", "1")
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "tab_title": f"{host} · Apto {apt} · Bayahibe",
            "footer_text": f"{host} · Bayahibe, RD",
            "headline_en": f"Welcome to Apto {apt}",
            "headline_es": f"Bienvenido al Apto {apt}",
            "headline_fr": f"Bienvenue à l'Apto {apt}",
            "tagline_en": "Need anything during your stay? Tap a service below.",
            "tagline_es": "¿Necesitas algo durante tu estadía? Toca un servicio.",
            "tagline_fr": "Besoin de quelque chose pendant votre séjour ? Touchez un service.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0002_service_description_fr_service_name_fr"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab_title",
                    models.CharField(
                        help_text="Browser tab title (single string, language-neutral).",
                        max_length=120,
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        help_text="Line shown in the page footer.", max_length=200
                    ),
                ),
                ("headline_en", models.CharField(max_length=160)),
                ("headline_es", models.CharField(max_length=160)),
                ("headline_fr", models.CharField(blank=True, max_length=160)),
                ("tagline_en", models.CharField(blank=True, max_length=240)),
                ("tagline_es", models.CharField(blank=True, max_length=240)),
                ("tagline_fr", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.RunPython(seed_singleton, reverse_code=migrations.RunPython.noop),
    ]
