# Generated by Django 6.0.5 on 2026-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0003_add_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Banner shown at the top of the service card on the landing page.",
                null=True,
                upload_to="services/",
            ),
        ),
    ]
