# Generated by Django 4.2.30 on 2026-08-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0004_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="delivery_error",
            field=models.TextField(
                blank=True,
                help_text="Why the send failed — usually an expired token or a closed 24-hour window.",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sent", "Sent"),
                    ("dry_run", "Dry run"),
                    ("failed", "Failed"),
                ],
                help_text="Outbound only. 'failed' means the guest or provider never received this.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["delivery_status", "created_at"],
                name="concierge_m_deliver_8bd001_idx",
            ),
        ),
    ]
