# Generated by Django 4.2.30 on 2026-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0005_message_delivery_error_message_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="referral_url",
            field=models.URLField(
                blank=True,
                help_text="Affiliate or referral link for this service (e.g. an Airbnb experience). Shown instead of the WhatsApp button when the landing page CTA mode uses referral links. Services without one fall back to WhatsApp.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_mode",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp only"),
                    (
                        "referral",
                        "Referral link only (WhatsApp used where no link is set)",
                    ),
                    ("both", "Referral link, with WhatsApp underneath"),
                ],
                default="whatsapp",
                help_text="What each service card links to. Referral modes need a Referral URL on the service; any service without one keeps its WhatsApp button so the card is never a dead end.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_cta_en",
            field=models.CharField(default="Book online", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_cta_es",
            field=models.CharField(default="Reservar online", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_cta_fr",
            field=models.CharField(default="Réserver en ligne", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_disclosure",
            field=models.CharField(
                blank=True,
                default="Some links are referral links — booking through them may earn us a commission at no extra cost to you.",
                help_text="Shown in the footer whenever referral links are on the page. Leave blank to hide.",
                max_length=200,
            ),
        ),
    ]
