# Generated by Django 4.2.30 on 2026-08-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0006_service_referral_url_sitesettings_cta_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="referral_url",
            field=models.URLField(
                blank=True,
                help_text="Affiliate or referral link for this service (e.g. an Airbnb experience). Paste the whole link — Airbnb's are long, and the listing_id near the end is what points at the right experience. Services without one fall back to WhatsApp.",
                max_length=800,
            ),
        ),
    ]
