# Generated by Django 4.2.30 on 2026-08-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0007_alter_service_referral_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name_es",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
