# Generated by Django 4.2.30 on 2026-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0008_alter_service_name_es"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="channel",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp — guest messages us"),
                    ("airbnb", "Airbnb — guest books via the referral link"),
                    ("viator", "Viator — guest books via the referral link"),
                ],
                default="whatsapp",
                help_text="Where this service's button sends guests. Airbnb and Viator both need a Referral URL below — without one the card falls back to WhatsApp so it is never a dead end.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="referral_url",
            field=models.URLField(
                blank=True,
                help_text="Affiliate or referral link, matching the channel above. Paste the whole link — Airbnb's are long, and the listing_id near the end is what points at the right experience.",
                max_length=800,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cta_mode",
            field=models.CharField(
                choices=[
                    (
                        "whatsapp",
                        "WhatsApp for everything (ignore each service's channel)",
                    ),
                    ("referral", "Use each service's own channel"),
                    ("both", "Use each service's channel, with WhatsApp underneath"),
                ],
                default="whatsapp",
                help_text="Site-wide switch over the per-service Channel. The first option is a kill switch that routes every card to WhatsApp — useful if a referral programme is paused.",
                max_length=20,
            ),
        ),
    ]
