# Generated by Django 4.2.30 on 2026-08-06 16:36

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0010_set_channel_from_existing_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="viator_campaign",
            field=models.CharField(
                blank=True,
                help_text="Optional label for your own reporting, e.g. apto-reef-qr.",
                max_length=60,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[A-Za-z0-9-]*$"),
                        "Letters, numbers and dashes only — other characters break Viator's tracking.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="viator_mcid",
            field=models.CharField(
                blank=True,
                help_text="Viator's tracking id for link placements. Leave blank to use 42383.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="viator_partner_id",
            field=models.CharField(
                blank=True,
                help_text="Your Viator affiliate PID, e.g. P00012345. Set this once and any plain viator.com product URL becomes a referral link — no need to build one per service.",
                max_length=32,
            ),
        ),
    ]
