# Generated by Django 4.2.30 on 2026-08-06 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0011_sitesettings_viator_campaign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to guests, e.g. “Restaurante La Bahía”.",
                        max_length=120,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The QR address: bookyourtickets.online/<slug>. Changing it orphans printed codes.",
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("apartment", "Holiday apartment"),
                            ("hotel", "Hotel"),
                            ("residence", "Residential building"),
                            ("restaurant", "Restaurant / bar"),
                            ("dive_shop", "Dive shop"),
                            ("supermarket", "Supermarket / shop"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "campaign_code",
                    models.SlugField(
                        blank=True,
                        help_text="Viator campaign for this venue — defaults to the slug. Letters, numbers and dashes only; anything else breaks Viator's attribution.",
                        max_length=60,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal — revenue share agreed, who to invoice, etc.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which services this venue shows. Leave empty to show all active ones. Use it to avoid advertising a venue's own competitors.",
                        related_name="locations",
                        to="concierge.service",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="LocationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scan", "Scan (landing page opened)"),
                            ("click", "Click (guest followed a service)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=20)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="concierge.location",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="concierge.service",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["location", "kind", "created_at"],
                        name="concierge_l_locatio_931722_idx",
                    )
                ],
            },
        ),
    ]
