# Generated by Django 4.2.30 on 2026-08-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0013_location_from_apartment_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="footer_text",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="location",
            name="headline_en",
            field=models.CharField(
                blank=True, help_text="The big line at the top.", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="headline_es",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="location",
            name="headline_fr",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="location",
            name="tab_title",
            field=models.CharField(
                blank=True,
                help_text="Browser tab title. Blank uses the site default.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="tagline_en",
            field=models.CharField(
                blank=True, help_text="The sentence under the headline.", max_length=240
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="tagline_es",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="location",
            name="tagline_fr",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
