# Generated by Django 4.2.30 on 2026-08-06 19:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0015_move_branding_to_the_reef"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="commission_share_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="This venue's cut, as a percentage of the commission you receive — not of the booking price. 20 means you keep 80%. Changing it only affects commissions recorded from now on.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_on",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date of the booking this commission is for.",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp — guest messages us"),
                            ("airbnb", "Airbnb — guest books via the referral link"),
                            ("viator", "Viator — guest books via the referral link"),
                        ],
                        help_text="Who owes you: the provider (WhatsApp), Airbnb, or Viator.",
                        max_length=20,
                    ),
                ),
                (
                    "gross_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The commission you earn, in USD. Not the price the guest paid.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Expected — not claimed yet"),
                            ("claimed", "Claimed / invoiced"),
                            ("received", "Received"),
                            ("written_off", "Written off"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "venue_share_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "venue_share_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("none", "No share due"),
                            ("owed", "Owed to the venue"),
                            ("paid", "Paid to the venue"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Booking or payout reference, for reconciling.",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which venue's QR produced it. Blank means it came from no particular venue.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="concierge.location",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="For WhatsApp referrals: the provider you claim this from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="concierge.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="concierge.service",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="concierge.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_on", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["status", "occurred_on"],
                        name="concierge_c_status_2b81eb_idx",
                    ),
                    models.Index(
                        fields=["payout_status", "occurred_on"],
                        name="concierge_c_payout__5c9ee9_idx",
                    ),
                    models.Index(
                        fields=["location", "occurred_on"],
                        name="concierge_c_locatio_2534d5_idx",
                    ),
                ],
            },
        ),
    ]
