# Generated by Django 4.2.30 on 2026-08-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0016_location_commission_share_pct_commission"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="concierge.location",
            ),
        ),
    ]
