# Generated by Django 4.2.30 on 2026-08-08 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("concierge", "0017_ticket_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="QrBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="What to call this run, e.g. “Bayahibe restaurants, August”.",
                        max_length=80,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal — who printed it, what stock, where they went.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "QR batches",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterField(
            model_name="location",
            name="campaign_code",
            field=models.SlugField(
                blank=True,
                help_text="How Viator attributes a booking to this venue — this is what a revenue share is paid on. Defaults to the slug; set one only if Viator asks for a particular format. Letters, numbers and dashes only.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="viator_mcid",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to send 42383, which is what Viator's own link builder emits for link placements.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="QrTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Printed on the card. This is what the QR encodes; it never changes.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="concierge.qrbatch",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where this card is stuck. Blank means it is still unassigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_tags",
                        to="concierge.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR tag",
                "ordering": ("token",),
            },
        ),
    ]
